src/survey/notes-screen.js, src/survey/survey-screen.js
fix bugs during navigation between questions
=> fix bugs in survey navigation

src/calendar/chart.js, src/common/constants.js, src/symptoms/symptoms-screen.js
* display point on graph
* start on the right question
=> fixs bugs (ui & navigation)

app/src/context/needUpdate.js, app/src/scenes/export/export.js, app/src/scenes/survey/daySurvey.js
Should fix sentry issues : 
MSP-3P
MSP-3J
MSP-2Z
=> fix: 3P, 3J, 2Z: optional .id .ok

api/Dockerfile
https://mattermost.fabrique.social.gouv.fr/default/pl/dxmk7u1ebtb6dqron16oirr7xh
=> chore(Dockerfile): lock Alpine version

.kontinuous/env/prod/values.yaml
=> fix: jm update resources

app/src/services/notifications-expo.js, app/src/services/notifications.ts
- Delete call to /user/:refreshToken
The api /user/:refreshToken does not exist. It seems to be a copy and paste code from ia suggestion.
- add missing import
=> fix: add missing uuid import, remove unexisting api call, add ts

app/src/navigation/router.tsx, app/src/navigation/tabs.js
=> feat: change statusbar color according to displayed route

app/src/components/JMButton.tsx, app/src/scenes/contribute/contributeCard.js
J'ai fait cette PR pour discuter aussi. Je crois que je ne comprends pas bien encore les approches pour les couleurs et les composants, et comme il y a beaucoup de composants je ne sais pas trop quelle approche prendre. J'ai essayé de prendre un fichier récent (JMButton) mais je ne sais pas si c'est comme ça qu'on veut faire (ni comment je dois l'étendre)
See: https://www.notion.so/fabnummas/Mettre-en-avant-le-CTA-permettant-de-donner-un-feedback-240653b7be0780bb84ced4b38d3fa9ba?source=copy_link
=> fix: mise en avant du CTA feedback

app/src/entities/Indicator.ts, app/src/scenes/onboarding-v2/CarouselScreen.tsx, app/src/scenes/onboarding-v2/IntroScreen.tsx, app/src/scenes/onboarding-v2/checkIn/OnboardingCheckInStartScreen.tsx, app/src/scenes/onboarding-v2/checkIn/mood/OnboardingCheckInHowDoYouFeelScreen.tsx, app/src/scenes/onboarding-v2/checkIn/sleep/OnboardingCheckInSleepScreen.tsx, app/src/scenes/onboarding-v2/data/helperData.tsx, app/src/scenes/onboarding-v2/index.tsx, app/src/scenes/onboarding-v2/indicators/OnboardingChooseIndicatorScreen.tsx, app/src/scenes/onboarding-v2/personalization/DifficultiesScreen.tsx, app/src/scenes/onboarding-v2/personalization/OnboardingPersonalizationStartScreen.tsx, app/src/scenes/onboarding-v2/personalization/SubCategoriesScreen.tsx, app/src/scenes/onboarding-v2/types.ts, app/src/scenes/reminder/reminderOnboarding.tsx, app/src/scenes/survey-v2/EncouragementScreen.tsx, app/src/scenes/survey-v2/SurveyScreenWrapper.tsx, app/src/services/logEvents.js, app/src/utils/liste_indicateurs.1.ts
J'ai laissé des notes sur ceux que je ne pouvais pas faire en attendant le retour de
=> feat: ajout des events de l'onboarding

app/src/components/drawer/index.js, app/src/services/NPS/NPS.js
https://www.notion.so/fabnummas/Mise-jour-des-infos-sur-l-cran-Nous-contacter-240653b7be0780058646f279cce86482?source=copy_link
j'ai galéré à coup de claude code sur celle là, impossible de m'en sortir tout seul, le flow est super exotique les trucs se fermaient et s'ouvraient dans tous les sens 🙃
=> fix: "Donner votre avis"  now open "Évaluer jardin mental"

app/src/scenes/goals/settings/GoalsSettingsMore.js
See: https://www.notion.so/fabnummas/Modifier-un-objectif-existant-25b653b7be07806ca4d5d24d0d473269?source=copy_link
=> fix: crash au click sur "modifier mes objectifs"

app/src/scenes/goals/settings/GoalDaySelector.tsx
fix https://www.notion.so/fabnummas/Modifier-un-objectif-Stylo-Je-ne-peux-pas-enregistrer-mes-modifs-25e653b7be078015b760f1e001dfac95?source=copy_link
=> fix: possibilité de sauvegarder la récurrence des objectifs

app/src/components/BackButton.js, app/src/components/MyText.js, app/src/scenes/beck/index.tsx
Puet-être lié à https://www.notion.so/fabnummas/Beck-App-crash-quand-je-veux-consulter-une-entr-e-pass-e-25e653b7be0780808e2dcedfab357f4c?source=copy_link
=> fix: beck save when changing date does not crash

app/src/scenes/survey/daySurvey.tsx
https://www.notion.so/fabnummas/Backlog-Jardin-Mental-1f2653b7be0780f0ad09f5d3eb8d22ca?p=247653b7be0780738eb8e04913f0fdb1&pm=s
=> chore: default to indicator.mainCategory

app/src/scenes/onboarding-v2/indicators/OnboardingChooseIndicatorScreen.tsx
Fix le 2ième commentaire de @pmallein :
https://www.notion.so/fabnummas/Backlog-Jardin-Mental-1f2653b7be0780f0ad09f5d3eb8d22ca?p=240653b7be07807f99ddfac4f1a4c137&pm=s
Dans selectedIndicator les uuid s'accumulaient le compte était donc faussé => ajout d'une sélection par catégories.
=> fix: add category-based indicator selection to fix inconsistent behavior

app/src/scenes/onboarding-v2/checkIn/mood/OnboardingCheckInHowDoYouFeelScreen.tsx
See: https://www.notion.so/fabnummas/Mes-analyses-Les-filtres-ne-fonctionnent-pas-sur-Android-25e653b7be0780018880e1b05b022abf?source=copy_link
=> fix: l'humeur du moment était rabaissée d'un cran dans l'onboarding

.talismanrc, app/App.tsx, app/src/services/NPS/NPS.js, app/src/services/NPS/NPSManager.js
La notification NPS est envoyé 4 fois actuellement car le composant NPS est utilisé à plusieurs endroit. On groupe la gestion de la notification NPS dans un service.
=> feat: add nps manager to prevent duplicate nps notification

app/app.json, app/package.json, app/yarn.lock
Pour tester que ça a marché :
```
adb shell dumpsys package com.monsuivipsy | grep targetSdk
```
=> fix: targetSdkVersion 35

app/App.tsx, app/package.json, app/src/scenes/dev-mode/index.tsx, app/yarn.lock
j'ai fait un build et tester le bouton dans le dev mode, je reçois bien les erreurs.
=> feat(sentry): add sentry

app/src/scenes/settings/settings-modal.tsx
…hould be scrollable
https://www.notion.so/fabnummas/Backlog-Jardin-Mental-1f2653b7be0780f0ad09f5d3eb8d22ca?p=215653b7be078091b7d3e49e881f4c8e&pm=s
=> feat(settings-modal): orientation should stay in landspace and view should be scrollable

app/src/scenes/onboarding-v2/CarouselScreen.tsx
On ne loggait pas le changement de slide en slidant (uniquement en cliquant sur next) ni en revenant en arrière
=> fix: slide change event on onbarding

app/src/components/Header.tsx, app/src/components/Icon.js
L'icon "settings" n'était pas bien aligné à droite.
=> chore: fix headers

app/src/scenes/support/SupportScreen.tsx
https://www.notion.so/fabnummas/Restructurer-la-rubrique-Ressources-pour-en-faire-un-parcours-d-apprentissage-sur-les-fondamentaux-d-277653b7be078037ac97ee316799cdc4?source=copy_link
=> fix: change "détresse" to "détresse suicidaire" for emergency phone number
